rule revil_decryption_tool {   
        meta:   
           author = "Chad Baxter"   
           author_email = "cbaxter@mail.umw.edu"   
           date = "2019-07-16"   
           updated = "2019-07-16"   
           description = "A rule to detect the REvil ransomware decryption tool"   
        strings:   
           $config_part0 = "{\"all\":"   
           $config_part1 = ",\"pc_sk\":\""   
           $config_part2 = "\",\"ext\":[\""   
      
           $pdb_path = "D:\\Code\\CSrc\\!1\\NEW_A\\TrumpIsGay\\"   
      
           $ransomware_distinguish0 = "---=== Welcome. Again. ===---"   
           $ransomware_distinguish1 = "/c vssadmin.exe Delete Shadows /All /Quiet"   
      
        condition:   
           any of ($config_part0, $config_part1, $config_part2, $pdb_path) and not ($ransomware_distinguish0 or $ransomware_distinguish1)   
}

rule revil_ransomware {   
        meta:   
           author = "Chad Baxter"   
           author_email = "cbaxter@mail.umw.edu"   
           date = "2019-07-16"   
           updated = "2019-07-16"   
           description = "A rule to detect the REvil ransomware"   
      
        strings:   
           $ransomware_distinguish0 = "---=== Welcome. Again. ===---[+] Whats Happen? [+]Your files are encrypted"   
           //$ransomware_distinguish1 = "/c vssadmin.exe Delete Shadows /All /Quiet"   
      
        condition:   
           $ransomware_distinguish0   
}

rule revil_domains {   
        meta:   
           author = "Chad Baxter"   
           author_email = "cbaxter@mail.umw.edu"   
           date = "2019-07-16"   
           updated = "2019-07-16"   
           description = "A rule to detect the REvil ransomware domains"   
      
        strings:   
             $a0 = "111firstdelray.com"   
             $b0 = "3daywebs.com"   
             $c0 = "5thactors.com"   
             $d0 = "acb-gruppe.ch"   
             $e0 = "activeterroristwarningcompany.com"   
             $f0 = "adedesign.com"   
             $g0 = "agenceassemble.fr"   
             $h0 = "airserviceunlimited.com"   
             $i0 = "airvapourbarrier.com"   
             $j0 = "alabamaroofingllc.com"   
             $k0 = "altitudeboise.com"   
             $l0 = "amelielecompte.wordpress.com"   
             $m0 = "aquacheck.co.za"   
             $n0 = "asiaartgallery.jp"   
             $o0 = "auberives-sur-vareze.fr"   
             $p0 = "awaitspain.com"   
             $q0 = "ayudaespiritualtamara.com"   
             $r0 = "banukumbak.com"   
             $s0 = "barbaramcfadyenjewelry.com"   
             $t0 = "bourchier.org"   
             $u0 = "breathebettertolivebetter.com"   
             $v0 = "bubbalucious.com"   
             $w0 = "buerocenter-butzbach-werbemittel.de"   
             $x0 = "bychowo.pl"   
             $y0 = "charlesfrancis.photos"   
             $z0 = "cleanroomequipment.ie"   
             $a1 = "computer-place.de"   
             $b1 = "cops4causes.org"   
             $c1 = "cp-bap.de"   
             $d1 = "cyberpromote.de"   
             $e1 = "denverwynkoopdentist.com"   
             $f1 = "devplus.be"   
             $g1 = "dibli.store"   
             $h1 = "dnqa.co.uk"   
             $i1 = "dogsunlimitedguide.com"   
             $j1 = "drbenveniste.com"   
             $k1 = "easydental.ae"   
             $l1 = "egpu.fr"   
             $m1 = "eurethicsport.eu"   
             $n1 = "fanuli.com.au"   
             $o1 = "fidelitytitleoregon.com"   
             $p1 = "focuskontur.com"   
             $q1 = "frimec-international.es"   
             $r1 = "funworx.de"   
             $s1 = "golfclublandgoednieuwkerk.nl"   
             $t1 = "gratiocafeblog.wordpress.com"   
             $u1 = "greenrider.nl"   
             $v1 = "hawaiisteelbuilding.com"   
             $w1 = "hiddensee-buhne11.de"   
             $x1 = "jaaphoekzema.nl"   
             $y1 = "jameswilliamspainting.com"   
             $z1 = "jlgraphisme.fr"   
             $a2 = "katherinealy.com"   
             $b2 = "latteswithleslie.com"   
             $c2 = "liveyourheartout.co"   
             $d2 = "look.academy"   
             $e2 = "makingmillionaires.net"   
             $f2 = "marcandy.com"   
             $g2 = "maxcube24.com.ua"   
             $h2 = "mazzaropi.com.br"   
             $i2 = "mensemetgesigte.co.za"   
             $j2 = "mieleshopping.it"   
             $k2 = "morgansconsult.com"   
             $l2 = "muni.pe"   
             $m2 = "myfbateam.com"   
             $n2 = "nexstagefinancial.com"   
             $o2 = "nuohous.com"   
             $p2 = "nutriwell.com.sg"   
             $q2 = "ocduiblog.com"   
             $r2 = "oro.ae"   
             $s2 = "outstandingminialbums.com"   
             $t2 = "pajagus.fr"   
             $u2 = "paprikapod.com"   
             $v2 = "physio-lang.de"   
             $w2 = "piestar.com"   
             $x2 = "projektparkiet.pl"   
             $y2 = "pvandambv.nl"   
             $z2 = "qwikcoach.com"   
             $a3 = "rapid5kloan.org"   
             $b3 = "rentingwell.com"   
             $c3 = "rentsportsequip.com"   
             $d3 = "rino-gmbh.com"   
             $e3 = "rsidesigns.com"   
             $f3 = "selected-minds.de"   
             $g3 = "signamedia.de"   
             $h3 = "slotspinner.com"   
             $i3 = "so-sage.fr"   
             $j3 = "spectamarketingdigital.com.br"   
             $k3 = "studionumerik.fr"   
             $l3 = "teamsegeln.ch"   
             $m3 = "terraflair.de"   
             $n3 = "tesisatonarim.com"   
             $o3 = "the-beauty-guides.com"   
             $p3 = "the3-week-diet.net"   
             $q3 = "tutvracks.com"   
             $r3 = "www.airserviceunlimited.com"   
             $s3 = "www.alabamaroofingllc.com"   
             $t3 = "www.cleanroomequipment.ie"   
             $u3 = "www.makingmillionaires.net"   
             $v3 = "wyreforest.net"   
             $w3 = "xrresources.com"   
             $x3 = "ykobbqchicken.ca"   
             $y3 = "ziliak.com"   
       condition:   
           any of them   
}
